spring.application.name=CampusConnect





server.port=8080


spring.datasource.url=jdbc:mysql://localhost:3306/campus_connect_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# --- JWT Secret Key ---
# REPLACE THIS with your own 256-bit (or 512-bit) secure key
jwt.secret-key=413F4428472B4B6250655368566D5970337336763979244226452948404D6351


# --- Razorpay Configuration ---
# Replace these with your actual Test Keys from Razorpay Dashboard
razorpay.key_id=rzp_test_RqODjBUvVW2YIl
razorpay.key_secret=ImBIV00QCijZ2KqJl3ndnnPM


# Cloudinary Configuration
cloudinary.cloud-name=doufqvfuz
cloudinary.api-key=622111652674717
cloudinary.api-secret=uQg7gLWHJ7CAwRD3r1Oed0g9sbA

